Repository Team-NumberOne/Backend, pull requests merged in 2023-11, with the labels that each got.

#45 Chore(#44) : 배포 타겟 브랜치 정리
  .github/workflows/cicd.yml
Labels: 🐧 infra

#48 Feat: Shelter API 관련 요구사항
  src/main/java/com/numberone/backend/domain/admin/controller/AdminController.java
  src/main/java/com/numberone/backend/domain/admin/dto/response/GetAddressResponse.java
  src/main/java/com/numberone/backend/domain/admin/service/AdminService.java
  src/main/java/com/numberone/backend/domain/shelter/repository/custom/CustomShelterRepository.java
  src/main/java/com/numberone/backend/domain/shelter/repository/custom/CustomShelterRepositoryImpl.java
  src/main/java/com/numberone/backend/support/S3Provider.java
Labels: 🚀 feature

#50 Feat: 재난문자 데이터 수집 및 위치기반 최근 재난문자 API 구현
  build.gradle
  src/main/java/com/numberone/backend/config/SchedulingConfig.java
  src/main/java/com/numberone/backend/domain/disaster/controller/DisasterController.java
  src/main/java/com/numberone/backend/domain/disaster/dto/request/LatestDisasterRequest.java
  src/main/java/com/numberone/backend/domain/disaster/dto/request/SaveDisasterRequest.java
  src/main/java/com/numberone/backend/domain/disaster/dto/response/DisasterDataResponse.java
  src/main/java/com/numberone/backend/domain/disaster/dto/response/LatestDisasterResponse.java
  src/main/java/com/numberone/backend/domain/disaster/entity/Disaster.java
  src/main/java/com/numberone/backend/domain/disaster/repository/DisasterRepository.java
  src/main/java/com/numberone/backend/domain/disaster/service/DisasterDataCollector.java
  src/main/java/com/numberone/backend/domain/disaster/service/DisasterService.java
  src/main/java/com/numberone/backend/domain/disaster/util/DisasterType.java
  src/main/java/com/numberone/backend/domain/token/service/TokenService.java
  src/main/java/com/numberone/backend/exception/badrequest/InvalidDisasterTypeException.java
  src/main/java/com/numberone/backend/exception/context/CustomExceptionContext.java
  src/main/java/com/numberone/backend/exception/notfound/NotFoundApiException.java
  src/main/java/com/numberone/backend/exception/notfound/NotFoundCrawlingException.java
  src/main/java/com/numberone/backend/properties/DisasterProperties.java
  src/main/java/com/numberone/backend/properties/KakaoProperties.java
  src/main/java/com/numberone/backend/util/LocationProvider.java
  src/main/java/com/numberone/backend/util/dto/MapApiResponse.java
Labels: 🚀 feature

#58 Feat: 후원 API 개발
  src/main/java/com/numberone/backend/domain/member/entity/Member.java
  src/main/java/com/numberone/backend/domain/sponsor/controller/SponsorController.java
  src/main/java/com/numberone/backend/domain/sponsor/dto/response/SponsorHomeResponse.java
  src/main/java/com/numberone/backend/domain/sponsor/dto/response/SponsorResponse.java
  src/main/java/com/numberone/backend/domain/sponsor/entity/Sponsor.java
  src/main/java/com/numberone/backend/domain/sponsor/repository/SponsorRepository.java
  src/main/java/com/numberone/backend/domain/sponsor/service/SponsorService.java
  src/main/java/com/numberone/backend/domain/support/controller/SupportController.java
  src/main/java/com/numberone/backend/domain/support/dto/request/CreateSupportRequest.java
  src/main/java/com/numberone/backend/domain/support/dto/request/EditMessageRequest.java
  src/main/java/com/numberone/backend/domain/support/dto/response/CreateSupportResponse.java
  src/main/java/com/numberone/backend/domain/support/entity/Support.java
  src/main/java/com/numberone/backend/domain/support/repository/SupportRepository.java
  src/main/java/com/numberone/backend/domain/support/service/SupportService.java
  src/main/java/com/numberone/backend/exception/context/CustomExceptionContext.java
  src/main/java/com/numberone/backend/exception/notfound/NotFoundSponsorException.java
  src/main/java/com/numberone/backend/exception/notfound/NotFoundSupportException.java
Labels: 🚀 feature

#59 Feat: 후원 이미지 및 url 추가, swagger 설명 추가
  src/main/java/com/numberone/backend/domain/sponsor/controller/SponsorController.java
  src/main/java/com/numberone/backend/domain/sponsor/dto/response/SponsorResponse.java
  src/main/java/com/numberone/backend/domain/sponsor/entity/Sponsor.java
  src/main/java/com/numberone/backend/domain/support/entity/Support.java
  src/main/java/com/numberone/backend/domain/support/service/SupportService.java
Labels: 🚀 feature

#61 Feat: 마음 구매 API 추가
  src/main/java/com/numberone/backend/domain/member/controller/MemberController.java
  src/main/java/com/numberone/backend/domain/member/dto/request/BuyHeartRequest.java
  src/main/java/com/numberone/backend/domain/member/dto/response/HeartCntResponse.java
  src/main/java/com/numberone/backend/domain/member/entity/Member.java
  src/main/java/com/numberone/backend/domain/member/service/MemberService.java
  src/main/java/com/numberone/backend/domain/support/dto/response/CreateSupportResponse.java
  src/main/java/com/numberone/backend/domain/support/service/SupportService.java
  src/main/java/com/numberone/backend/exception/badrequest/BadRequestHeartException.java
  src/main/java/com/numberone/backend/exception/context/CustomExceptionContext.java
Labels: 🚀 feature

#62 Feat: 온보딩 API 구현
  src/main/java/com/numberone/backend/domain/member/controller/MemberController.java
  src/main/java/com/numberone/backend/domain/member/dto/request/OnboardingAddress.java
  src/main/java/com/numberone/backend/domain/member/dto/request/OnboardingDisasterType.java
  src/main/java/com/numberone/backend/domain/member/dto/request/OnboardingRequest.java
  src/main/java/com/numberone/backend/domain/member/entity/Member.java
  src/main/java/com/numberone/backend/domain/member/service/MemberService.java
  src/main/java/com/numberone/backend/domain/notificationdisaster/entity/NotificationDisaster.java
  src/main/java/com/numberone/backend/domain/notificationdisaster/repository/NotificationDisasterRepository.java
  src/main/java/com/numberone/backend/domain/notificationregion/entity/NotificationRegion.java
  src/main/java/com/numberone/backend/domain/notificationregion/repository/NotificationRegionRepository.java
  src/main/java/com/numberone/backend/domain/token/dto/response/KakaoInfoResponse.java
  src/main/java/com/numberone/backend/domain/token/service/TokenService.java
Labels: 🚀 feature

#69 Fix(#68): 온보딩시 fcm토큰 설정 추가
  src/main/java/com/numberone/backend/domain/member/controller/MemberController.java
  src/main/java/com/numberone/backend/domain/member/dto/request/OnboardingRequest.java
  src/main/java/com/numberone/backend/domain/member/entity/Member.java
  src/main/java/com/numberone/backend/domain/member/service/MemberService.java
Labels: 🚑 hotfix

#72 Feat: 재난상황 API 구현
  src/main/java/com/numberone/backend/domain/conversation/controller/ConversationController.java
  src/main/java/com/numberone/backend/domain/conversation/dto/request/CreateChildConversationRequest.java
  src/main/java/com/numberone/backend/domain/conversation/dto/request/CreateConversationRequest.java
  src/main/java/com/numberone/backend/domain/conversation/dto/response/GetConversationResponse.java
  src/main/java/com/numberone/backend/domain/conversation/entity/Conversation.java
  src/main/java/com/numberone/backend/domain/conversation/repository/ConversationRepository.java
  src/main/java/com/numberone/backend/domain/conversation/service/ConversationService.java
  src/main/java/com/numberone/backend/domain/disaster/controller/DisasterController.java
  src/main/java/com/numberone/backend/domain/disaster/dto/response/SituationDetailResponse.java
  src/main/java/com/numberone/backend/domain/disaster/dto/response/SituationHomeResponse.java
  src/main/java/com/numberone/backend/domain/disaster/dto/response/SituationResponse.java
  src/main/java/com/numberone/backend/domain/disaster/entity/Disaster.java
  src/main/java/com/numberone/backend/domain/disaster/repository/DisasterRepository.java
  src/main/java/com/numberone/backend/domain/disaster/service/DisasterService.java
  src/main/java/com/numberone/backend/domain/like/entity/ConversationLike.java
  src/main/java/com/numberone/backend/domain/like/repository/ConversationLikeRepository.java
  src/main/java/com/numberone/backend/domain/member/entity/Member.java
  src/main/java/com/numberone/backend/exception/badrequest/BadRequestConversationSortException.java
  src/main/java/com/numberone/backend/exception/context/CustomExceptionContext.java
  src/main/java/com/numberone/backend/exception/notfound/NotFoundConversationException.java
  src/main/java/com/numberone/backend/exception/notfound/NotFoundDisasterException.java
Labels: 🚀 feature

#79 Feat: 사용자 GPS 위치 변경 및 온/오프라인 상태 변경 API 구현
  src/main/java/com/numberone/backend/domain/member/controller/MemberController.java
  src/main/java/com/numberone/backend/domain/member/dto/request/UpdateGpsRequest.java
  src/main/java/com/numberone/backend/domain/member/dto/response/MemberIdResponse.java
  src/main/java/com/numberone/backend/domain/member/entity/Member.java
  src/main/java/com/numberone/backend/domain/member/service/MemberService.java
Labels: 🚀 feature

#81 Fix(#80): 재난상황-커뮤니티 대댓글 정렬기준 오래된순으로 수정
  src/main/java/com/numberone/backend/domain/conversation/repository/ConversationRepository.java
  src/main/java/com/numberone/backend/domain/conversation/service/ConversationService.java
Labels: 🚑 hotfix

#82 Fix(#67): 후원페이지에서 이메일이 아니라 닉네임 정보가 보여지도록 수정
  src/main/java/com/numberone/backend/domain/sponsor/service/SponsorService.java
Labels: 🚀 feature

#83 Hotfix: memory issue
  src/main/java/com/numberone/backend/domain/disaster/service/DisasterDataCollector.java
Labels: 🚑 hotfix

#86 Fix(#85): 재난상황 댓글 날짜형식 수정
  src/main/java/com/numberone/backend/domain/conversation/dto/response/GetConversationResponse.java
Labels: 🚑 hotfix

#88 Fix: 홈 재난문자 api 온보딩 정보 반영 & 재난문자 카테고리 수정
  src/main/java/com/numberone/backend/domain/disaster/controller/DisasterController.java
  src/main/java/com/numberone/backend/domain/disaster/repository/DisasterRepository.java
  src/main/java/com/numberone/backend/domain/disaster/service/DisasterDataCollector.java
  src/main/java/com/numberone/backend/domain/disaster/service/DisasterService.java
  src/main/java/com/numberone/backend/domain/disaster/util/DisasterType.java
Labels: 🚑 hotfix

#94 Fix: 온라인 전환 api 응답값 닉네임, 실명 추가
  src/main/java/com/numberone/backend/domain/member/dto/response/MemberIdResponse.java
  src/main/java/com/numberone/backend/domain/member/service/MemberService.java
Labels: 🚑 hotfix
