Repository Team-NumberOne/Backend, pull requests merged in 2023-10, with the labels that each got.

#4 Feat: CI/CD 환경 구축
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  settings.gradle
  src/main/java/com/numberone/backend/HelloController.java
  src/main/java/com/numberone/backend/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: enhancement

#7 Feat: 예외는 한 곳에서 처리한다.
  build.gradle
  src/main/java/com/numberone/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/numberone/backend/exception/NumberOneException.java
  src/main/java/com/numberone/backend/exception/badrequest/BadRequestException.java
  src/main/java/com/numberone/backend/exception/context/CustomExceptionContext.java
  src/main/java/com/numberone/backend/exception/context/ExceptionContext.java
  src/main/java/com/numberone/backend/exception/dto/ErrorResponse.java
  src/main/java/com/numberone/backend/exception/notfound/NotFoundException.java
  src/main/java/com/numberone/backend/exception/notfound/NotFoundMemberException.java
Labels: 🚀 feature

#11 Feat: Swagger, QueryDSL, JPA 셋업 / 대피소 DB 구축
  .github/workflows/cicd.yml
  build.gradle
  src/main/java/com/numberone/backend/config/P6spyLogMessageFormatConfiguration.java
  src/main/java/com/numberone/backend/config/P6spySqlFormatConfiguration.java
  src/main/java/com/numberone/backend/config/SecurityConfig.java
  src/main/java/com/numberone/backend/config/SwaggerConfig.java
  src/main/java/com/numberone/backend/config/basetime/BaseTimeConfig.java
  src/main/java/com/numberone/backend/config/basetime/BaseTimeEntity.java
  src/main/java/com/numberone/backend/domain/shelter/entity/Shelter.java
  src/main/java/com/numberone/backend/domain/shelter/repository/ShelterRepository.java
  src/main/java/com/numberone/backend/domain/shelter/service/ShelterService.java
  src/main/java/com/numberone/backend/domain/shelter/util/Address.java
  src/main/java/com/numberone/backend/domain/shelter/util/ShelterStatus.java
Labels: 📚 documentation, 🚀 feature

#15 Feat: 내 주변 대피소 위치 반환 API 구현
  src/main/java/com/numberone/backend/HelloController.java
  src/main/java/com/numberone/backend/config/SecurityConfig.java
  src/main/java/com/numberone/backend/domain/shelter/controller/ShelterController.java
  src/main/java/com/numberone/backend/domain/shelter/dto/request/NearbyShelterRequest.java
  src/main/java/com/numberone/backend/domain/shelter/dto/response/NearbyShelterListResponse.java
  src/main/java/com/numberone/backend/domain/shelter/dto/response/NearestShelterResponse.java
  src/main/java/com/numberone/backend/domain/shelter/dto/response/ShelterMapper.java
  src/main/java/com/numberone/backend/domain/shelter/repository/ShelterRepository.java
  src/main/java/com/numberone/backend/domain/shelter/service/ShelterService.java
  src/main/java/com/numberone/backend/domain/shelter/util/Address.java
  src/main/java/com/numberone/backend/exception/context/CustomExceptionContext.java
  src/main/java/com/numberone/backend/exception/notfound/NotFoundShelterException.java
Labels: 📚 documentation, 🚀 feature

#20 Feat: shelters api 인가 처리 disable
  src/main/java/com/numberone/backend/config/SecurityConfig.java
Labels: 🐛 bug

#27 Feat: swagger 에서 jwt 토큰 인증 가능하도록 변경
  src/main/java/com/numberone/backend/config/SecurityConfig.java
  src/main/java/com/numberone/backend/config/SwaggerConfig.java
  src/main/java/com/numberone/backend/domain/shelter/controller/ShelterController.java
Labels: 📚 documentation, 🚀 feature

#29 Feat: 토큰 발급 api 응답형식 수정 및 여러 커스텀 예외 추가
  .github/workflows/cicd.yml
  src/main/java/com/numberone/backend/LoginTestController.java
  src/main/java/com/numberone/backend/config/auth/JwtFilter.java
  src/main/java/com/numberone/backend/domain/token/controller/TokenController.java
  src/main/java/com/numberone/backend/domain/token/dto/request/GetTokenRequest.java
  src/main/java/com/numberone/backend/domain/token/dto/request/RefreshTokenRequest.java
  src/main/java/com/numberone/backend/domain/token/dto/request/TokenRequest.java
  src/main/java/com/numberone/backend/domain/token/dto/response/GetTokenResponse.java
  src/main/java/com/numberone/backend/domain/token/dto/response/RefreshTokenResponse.java
  src/main/java/com/numberone/backend/domain/token/dto/response/TokenResponse.java
  src/main/java/com/numberone/backend/domain/token/entity/Token.java
  src/main/java/com/numberone/backend/domain/token/repository/TokenRepository.java
  src/main/java/com/numberone/backend/domain/token/service/TokenService.java
  src/main/java/com/numberone/backend/domain/token/util/JwtUtil.java
  src/main/java/com/numberone/backend/exception/badrequest/BadRequestSocialTokenException.java
  src/main/java/com/numberone/backend/exception/badrequest/BadRequestTokenException.java
  src/main/java/com/numberone/backend/exception/context/CustomExceptionContext.java
  src/main/java/com/numberone/backend/exception/dto/ErrorResponse.java
  src/main/java/com/numberone/backend/exception/forbidden/ExpiredAccessTokenException.java
  src/main/java/com/numberone/backend/exception/forbidden/ForbiddenException.java
  src/main/java/com/numberone/backend/exception/forbidden/WrongAccessTokenException.java
  src/main/java/com/numberone/backend/exception/notfound/NotFoundRefreshTokenException.java
Labels: 🚀 feature

#36 Fix(#35): 토큰 갱신시 refresh token도 함께 갱신되도록 수정
  src/main/java/com/numberone/backend/domain/token/dto/response/RefreshTokenResponse.java
  src/main/java/com/numberone/backend/domain/token/entity/Token.java
  src/main/java/com/numberone/backend/domain/token/service/TokenService.java
Labels: 🐛 bug

#39 Feat: s3 storage 기본 셋업
  build.gradle
  src/main/java/com/numberone/backend/config/S3Config.java
  src/main/java/com/numberone/backend/exception/badrequest/FileMissingException.java
  src/main/java/com/numberone/backend/exception/badrequest/FileUploadException.java
  src/main/java/com/numberone/backend/exception/context/CustomExceptionContext.java
  src/main/java/com/numberone/backend/support/S3Provider.java
Labels: 🚀 feature, 🐧 infra
